sudo: required
services:
- docker
env:
  global:
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - BUILD_VERSION=$(date +"%y%m")

jobs:
  include:
  - stage: linter
    script:
    - make linter

  - stage: build
    script:
    - make

  - stage: build and push docker image
    script:
    - make
    - make push
