#!/bin/bash

docker login \
  --username "${DOCKER_USERNAME}" \
  --password "${DOCKER_PASSWORD}"

docker push \
    ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:latest

docker tag \
    ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:latest \
    ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_VERSION}

docker push \
    ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${BUILD_VERSION}

docker logout
